export const FORM_ACTIONS = {
  VER: "VER",
  CREAR: "CREAR",
  MODIFICAR: "MODIFICAR",
};

export const diasSemana = [
  { display: 'Lunes', value: 'LU', value2: 'lunes' },
  { display: 'Martes', value: 'MA', value2: 'martes' },
  { display: 'Miércoles', value: 'MI', value2: 'miercoles' },
  { display: 'Jueves', value: 'JU', value2: 'jueves' },
  { display: 'Viernes', value: 'VI', value2: 'viernes' },
  { display: 'Sábado', value: 'SA', value2: 'sabado' },
  { display: 'Domingo', value: 'DO', value2: 'domingo' },
];

export const AREAS_USUARIOS = {
  SECCIONAL: 1,
  NACIONAL: 2,
  RECURSOS_HUMANOS: 3,
  CONTRATACIONES: 4,
  LEGALES: 5,
  CENTROS_MEDICOS: 6,
  COMUNICACIONES: 8,
  LIQUIDACIONES: 9,
  AUTORIZACIONES: 10,
  ALBERTI: 15,
  MATHEU: 16,
  TOTEM: 17,
  DISCAPACIDAD: 18,
  MESA_ENTRADA: 19,
};

export const SUB_AREAS_CONTRATACIONES = {
  COMPLETA: 1,
  RRHH: 2,
  LEGALES: 3
};

export const TIPO_PARAMETRIZACION_TURNOS = {
  NORMAL: 1,
  EVENTUAL: 2,
};

export const FRECUENCIA_TURNOS = {
  DIARIO: 1,
  SEMANAL: 2,
  QUINCENAL: 3,
  MENSUAL: 4,
};

export const SITUACION_REVISTA = {
  RELACION_DE_DEPENDENCIA: 0,
  PASANTES: 1,
  JUBILADOS_DEL_SISTEMA_NACIONAL_DEL_SEGURO_DE_SALUD: 2,
  ADHERENTES_VOLUNTARIOS: 3,
  MONOTRIBUTISTA: 4,
  SERVICIO_DOMESTICO: 5,
  MONOTRIBUTISTA_SOCIAL: 7,
  SEGURO_DESEMPLEO: 8,
  RELACION_DE_DEPENDENCIA_SIN_APORTES: 12,
};
export const TIPO_AFILIACION = {
  DJ: 1,
  TRASPASO: 2,
  TEMPORARIO_CON_CUOTA: 4,
  TEMPORARIO: 57,
  PASANTE: 62,
  ADHERENTE: 63,
  JUBILADOS_NACIONAL: 64,
  JUBILADOS_ESPANOLES: 65,
  JUBILADOS_PENSIONADOS_OTROS_SISTEMAS: 66,
  FONDO_DESEMPLEO: 67,
  FONDO_DESEMPLEO_RENATRE: 68,
  SERVICIO_DOMESTICO: 69,
  MONOTRIBUTISTA_SOCIAL: 70,
  MONOTRIBUTISTA: 71,
  EMPADRONADO: 72,
  TRASPASO_MR: 73,
};
export const PARENTESCOS = {
  TITULAR: 0,
  CONYUGE: 1,
  CONCUBINA_O: 2,
  HIJO_MENOR: 3,
  HIJO_ESTUDIANTE: 4,
  FAMILIAR_A_CARGO: 5,
  HIJO_DISCAPACITADO: 6,
  MENOR_BAJO_GUARDA_O_TUTELA: 7,
  HIJO_CONYUGE: 8,
  HIJO_CONYUGE_ESTUDIANTE: 9,
};
export const SEXO = {
  MASCULINO: 1,
  FEMENINO: 2,
  NO_INFORMADO: 3,
};
export const TIPO_DOCUMENTO = {
  DNI: 1,
  CEDULA_IDENTIDAD: 2,
  LIBRETA_ENROLAMIENTO: 3,
  LIBRETA_CIVICA: 4,
  PASAPORTE: 5,
  NI: 6,
  RN: 7,
};
export const ESTADOS_CIVILES = {
  CASADO: 1,
  SOLTERO: 2,
  SEPARADO: 3,
  DIVORCIADO: 4,
  VIUDO: 5,
  CONCUBINO: 6,
  OTRO: 7,
};

export const TIPO_CERTIFICADOS = {
  ESTUDIO: 1,
  DISCAPACIDAD: 2,
  PMI: 3,
};

export const CENTROS_MEDICOS_PROPIOS = {
  TALIANO: 1,
  ESCOBAR: 2,
  TIGRE: 3,
  CORDOBA_CAPITAL: 4,
  LA_PLATA: 6,
  SANTA_FE: 7,
  DORREGO_MDQ: 8,
  URQUIZA_ENTRE_RIOS: 9,
  SALTA: 10,
  PUNILLA_CORDOBA: 12,
  MORON: 13,
  BONJOUR_LOMAS_DE_ZAMORA: 14,
  VARELA_BERAZATEGUI: 15,
};

export const TAMANO_IMAGENES = {
  CERTIFICADOS: 3072 * 1024,
  DOCUMENTACION_AFILIADOS: 3072 * 1024,
  FOTO_USUARIO: 3072 * 1024,
};

export const MOTIVO_TURNOS = {
  CANCELADO_POR_AFILIADO: 1,
};

export const ESTADOS_EFECTOR = {
  ACTIVO: 1,
  PASIVO: 2,
};

export const CATEGORIAS_TIPO_DOCUMENTACION = {
  DATOS_PERSONALES: 1,
  EMPRESA: 2,
  DATOS_LEGALES: 3
};

export const TIPO_TURNO = {
  PRESENCIAL: 1,
  VIRTUAL: 2,
  AMBOS: 3,
};

export const TIPO_FERIADO = {
  FERIADO_NACIONAL: 1,
  FERIADO_PROVINCIAL: 2,
  FERIADO_CIUDAD: 3,
};

export const TIPO_COMPROBANTE = {
  FACTURA: 1,
  NOTA_CREDITO: 2,
  PRESUPUESTO: 3,
  NOTA_DEBITO: 4,
  RECIBO: 5,
  PROFORMA: 6,
  COTIZACION: 7
};

export const SUBTIPO_EFECTORES = {
  ENTIDADES_INTERMEDIAS_PROFESIONALES: 2,
  PROFESIONALES_CENTROS_AJENOS: 6,
  PROFESIONALES_CENTROS_PROPIOS: 7,
  ENTIDADES_INTERMEDIAS_ESTABLECIMIENTOS_REDES_GERENCIADORAS: 8,
  PERSONAS_JURIDICAS: 9,
  EVENTUAL: 10,
  FARMACIA: 11,
  HOSPITAL: 12,
  INTEGRACION: 13,
  NO_RECUPERABLES: 14,
  ADICCION: 15,
  ENFERMERIA: 16,
  PROVEEDOR: 17,
  COMPRAS_MEDICAS: 18,
};

export const NOMENCLADORES = {
  NOMENCLADOR_OSPEDYC: 1,
  NOMENCLADOR_HOSPITALES_CABA: 2,
  NOMENCLADOR_HOSPITALES_PUBLIC: 3,
  NOMENCLADOR_ODONTOLOGICO: 4,
  NOMENCLADOR_GARRAHAN: 5,
  SIN_DENOMINACION: 6,
};

export const TIPO_EFECTORES = {
  //tipo contratos
  CONTRATO_PRESTADORES: 1,
  INTEGRACION: 2,
  PROVEEDOR: 3,
};

export const TIPO_CONTACTO_EFECTOR = {
  LEGAL:  1,
  FACTURACION: 2,
  COMERCIAL: 3,
  TESORERIA: 4,
  DIRECCION_MEDICA: 5,
  AUDITORIA: 6,
  ADMISIONES_INTERNACION: 7,
  NO_INDICA: 8
}

export const TIPO_MATRICULA = {
  MATRICULA_NACIONAL: 1,
  MATRICULA_PROVINCIAL: 2,
  MATRICULA_MUNICIPAL: 3,
};

export const TIPOS_ARCHIVOS_MIGRACION = {
  PADRON_SSS: 6,
  NOVEDADES_SSS: 9,

  BAJAS: 17,
  CAPITA_DESEMPLEO: 5,
  CAPITA_JUBILADOS: 4,
  DDJJ: 1,
  DEVOLUCIONES_SSS: 8,
  ENVIO_PADRON_SSS: 11,
  PAGO_FACIL: 16,
  RELACIONES_LABORALES: 3,
  SANO: 12,
  SUBSIDIOS: 7,
  SUMA: 13,
  SUMA_70: 14,
  SUMARTE: 15,
  TRANSFERENCIAS: 2,
};

export const TIPOS_ARCHIVOS_CONTRATACIONES = {
  CMP: 1,
  EQUIVALENCIAS: 2,
  MODULOS: 3,
};

export const MENU_CONTRATACIONES = {
  CONSULTA: 1,
  INGRESO: 2,
};

export const MENU_PROVEEDORES = {
  CONSULTA: 1,
  INGRESO: 2,
};

export const VERSIONADO = {
  VERSION_ACTUAL: "v2023.06.06",
};

export const BUSCADOR_CENTRAL = {
  CARACTERES_MINIMOS_AFILIACIONES: 2,
  MILISEG_SIN_CAMBIOS: 2000
}

export const TIPO_PRACTICAS_POR_FECHA = {
  NO_VIGENTES: 1,
  VIGENTES: 2,
  FUTURAS: 3,
};

export const CATEGORIAS_VALORIZACIONES = {
  A: 1,
  B: 2,
  C: 3,
  BASICA: 4,
  D: 5,
  ND: 6
};

export const CATEGORIAS_VALORIZACIONES_ARRAY = [
  {id : CATEGORIAS_VALORIZACIONES.BASICA, descripcion: "Basica"},
  {id : CATEGORIAS_VALORIZACIONES.A, descripcion: "A"},
  {id : CATEGORIAS_VALORIZACIONES.B, descripcion: "B"},
  {id : CATEGORIAS_VALORIZACIONES.C, descripcion: "C"},
  {id : CATEGORIAS_VALORIZACIONES.D, descripcion: "D"},
  {id : CATEGORIAS_VALORIZACIONES.ND, descripcion: "N/D"}
];

export const TIPOS_VALORIZACIONES = {
  VALOR_FIJO: 1,
  NBU: 2,
  NNX: 3,
  GALENOS_GASTOS: 4,
};

export const CAT_HONGAS_VALORIZACIONES = {
  H: 1,
  G: 2,
  HG: 3,
};

export const CARTILLAS = {
  ADICCIONES_DISCAPACIDAD: 23,
};

export const TIPO_NOTIFICACIONES = {
  APP: 1,
  EMAIL: 2,
  SMS: 3,
};

export const RANKINGS_CARTILLA = {
  CM_PROPIO: 1,
};

export const MENU_LIQUIDACIONES = {
  GESTION_FACTURAS: 1,
};

export const LIQUIDACIONES_COMPROBANTES_ESTADOS = {
  PENDIENTE_CARGA: 1,            //en MesaEntradas es Pendiente envio
  // ENVIADA: 3,         //ESTE ESTADO ES CUANDO SE RETORNO EL COMPROBANTE 
  PENDIENTE_LIQUIDACION: 4,
  PENDIENTE_SOLICITUD_PAGO: 5,
  PENDIENTE_ENVIO_TESORERIA: 6,
  ENVIADA_TESORERIA: 7,
  // RETORNADA: 8,
  ANULADA: 2,
  PAGADA: 9,
};

export const LIQUIDACIONES_LINEA_COMPORBANTE = {
  PRESTACION: 1,
  MEDICAMENTO: 2,
  INSUMO: 3
}

export const LIQUIDACIONES_TIPO_INGRESO_LINEA = {
  CARGA_EXCEL: 1,
  CARGA_MANUAL: 2,
  CARGA_POR_IDSOLICITUD: 3
}

export const PRACTICA_ERROR_SUMA = {
  ID_COD_NOM: 8685,
  COD_NOM: "xx.xx.xx",
  DES_NOM: "ERROR DE SUMA",
};

export const PRACTICA_PRORROGA_AUTOMATICA = {
  ID_COD_NOM: 8686,
  COD_NOM: "yy.yy.yy",
  DES_NOM: "PRORROGA AUTOMATICA",
};

export const PRACTICA_EMPADRONAMIENTO = {
  ID_COD_NOM: 8811,
  COD_NOM: "80.50.15",
  DES_NOM: "EMPADRONAMIENTO",
};

export const MENU_AUTORIZACIONES = {
  INGRESO_AUTORIZACION: 1,
  GESTION_AUDITORIA: 2,
  GESTION_PRESUPUESTOS: 3,
  SOLICITUDES_VIA_APP: 4,
};

export const STEPPER_AUTORIZACIONES = {
  BUSCAR_TITULAR: 0,
  DATOS_TITULAR: 1,
  DETALLES_ORDEN: 2,
  PRACTICAS: 3,
  CONFIRMACION: 4,
};

export const TIPOS_AUTORIZACIONES = {
  PRACTICAS: 1,
  MATERIALES_SIN_PRACTICAS: 2,
  PRACTICAS_DOMICILIARIAS: 3,
  PRESUPUESTOS: 4,
  TRASLADO: 5,
  DENUNCIA_INTERNACION: 6,
  DENUNCIA_INTERNACION_DOMICILIARIA: 7,
  DISCAPACIDAD: 8,
};

export const TIPOS_PRESUPUESTO = {
  CON_CONTRATO: 1,
  SIN_CONTRATO: 2,
}; 

export const PRACTICA_INSUMOS_AUTORIZACIONES = {
  ID_COD_NOM: 8576,
  COD_NOM: "80.50.06",
  DES_NOM: "INSUMOS MEDICOS",
};

export const ESTADISTICAS_OSPEDYC = {
  INGRESOS_MOBILE: 1,
  INGRESOS_DESKTOP: 2,
  TIEMPO_DE_USO: 3,
  CREDENCIAL: 4,
  TURNOS: 5,
  CARTILLA: 6,
  FORMULARIOS: 7,
  FARMACIAS: 8,
  CONTACTOS: 9,
  DISCAPACIDAD: 10,
};

export const AUTORIZACIONES_SOLICITUDES_ESTADOS = {
  EN_CARGA: 1,
  PENDIENTE: 2,
  DEVOLUCION: 3,
  PENDIENTE_MATERIALES: 5,
  AUDITORIA_ADMINISTRATIVA: 6,
  INTERNACION_DOMICILIARIA: 94,   //SOLO PARA AGRUPAR idEstado Real = 2 PENDIENTE
  AUDITORIA_TERRENO: 96,          //SOLO PARA AGRUPAR idEstado Real = 2 PENDIENTE
  INTERNACION_PAIS: 97,           //SOLO PARA AGRUPAR idEstado Real = 2 PENDIENTE
  TERMINADA: 4,
  PENDIENTE_COBRO: 93,            //SOLO PARA AGRUPAR idEstado Real = 4 TERMINADA
  CANCELADA: 95,                  //SOLO PARA AGRUPAR idEstado Real = 4 TERMINADA
  RECHAZADA: 98,                  //SOLO PARA AGRUPAR idEstado Real = 4 TERMINADA
  AUTORIZADA: 99,                 //SOLO PARA AGRUPAR idEstado Real = 4 TERMINADA
};

export const AUTORIZACIONES_PRESUPUESTOS_ESTADOS = {
  EN_CARGA: 1,
  PENDIENTE: 2,
  AUDITORIA: 3,
  PENDIENTE_CONTRATOS: 4,
  AUTORIZADO: 5,
  RECHAZADO: 6,
};

export const AUTORIZACIONES_PRACTICAS_ESTADOS = {
  PENDIENTE: 1,
  AUTORIZADO: 2,
  RECHAZADO: 3,
  GESTION: 4,
  TERMINADA: 5
};

export const AUTORIZACIONES_MATERIALES_ESTADOS = {
  PENDIENTE: 1,
  AUTORIZADO: 2,
  RECHAZADO: 3,
  GESTION: 4,
};

export const AUTORIZACIONES_MENU_AUDITORIA = {
  AFILIADO: 0,
  ADMINISTRAR: 1,
  INFORMACION: 2,
  PRACTICAS: 3,
  NOTAS: 4,
  OBSERVACIONES: 5,
};

export const AUTORIZACIONES_TIPOS_NOTAS = {
  PRIVADA: 1,
  PUBLICA: 2,
};

export const AUTORIZACIONES_BANDEJAS = {
  AUDITOR_MEDICO: 1,
  AUDITOR_TRAUMATOLOGICO: 2,
  AUDITOR_ONCOLOGICO: 3,
  COMPRAS: 4,
  FISIATRIA: 5,
  DIRECCION_MEDICA: 6,
  JEFATURA_AUDITORIA_MEDICA: 7,
  AUDITORIA_ADMINISTRATIVA: 8,
  AUDITORIA_TERRENO: 9,
  INTERNACION_PAIS: 10,
  AUDITOR_PRESUPUESTOS: 11,
  CONTRATOS: 12,
  INTERNACION_DOMICILIARIA: 13,
};

export const AUTORIZACIONES_MENU_HISTORIAL = {
  SOLICITUD: 0,
  PRESUPUESTO: 0,
  PRACTICA: 1,
  MATERIAL: 2,
  PERIODO_PRACTICA: 3,
};

export const AUTORIZACIONES_TIPO_EFECTOR = {
  INSTITUCIONAL: 1,
  PROFESIONAL: 2,
  INSTITUCIONAL_Y_PROFESIONAL: 3,
  INSTITUCINOAL_DISPONIBLE: 4,    //DENUNCIA INTERNACION
}

export const AUTORIZACIONES_COBRA_COSEGURO = {
  SI: 1,
  NO: 2,
  COBRA_CAB: 3
}

export const PRACTICA_APERTURA_DENUNCIA_INTERNACION = {
  ID_COD_NOM: 5259,
  COD_NOM: "43.01.10",
  DES_NOM: "APERTURA DENUNCIA DE INTERNACION",
};

export const PRACTICA_CIERRE_DENUNCIA_INTERNACION = {
  ID_COD_NOM: 5260,
  COD_NOM: "43.01.11",
  DES_NOM: "CIERRE DENUNCIA DE INTERNACION",
};

export const PRACTICA_APERTURA_INTERNACION_DOMICILIARIA = {
  ID_COD_NOM: 8683,
  COD_NOM: "99.99.10",
  DES_NOM: "APERTURA DE INTERNACION DOMICILIARIA",
};

export const PRACTICA_CIERRE_INTERNACION_DOMICILIARIA = {
  ID_COD_NOM: 8684,
  COD_NOM: "99.99.11",
  DES_NOM: "CIERRE DE INTERNACION DOMICILIARIA",
};

export const TIPO_TRACKING_ABM = {
  NOMENCLADOR_BANDEJA: 1,
  EFECTOR_AUDITOR_TERRENO: 2,
  NOMENCLADOR_NACIONAL: 3,
  GRUPO_COSEGURO: 4
};

export const MOTIVOS_BAJA_TURNOS = {
  CANCELADO_POR_AFILIADO: 20,
  CANCELADO_POR_PROFESIONAL: 2,
  ERROR_AGENDA_MEDICA: 3,
  VACACIONES: 8,
  FERIADO: 21,
};

export const GASTOS_NOMENCLADOR=[
  {
    id: 1,
    descripcion:"Galeno"
  },
  {
    id: 2,
    descripcion:"Gasto Quirurgico"
  },
  {
    id: 3,
    descripcion:"Otros Gastos"
  },
  {
    id: 4,
    descripcion:"Honorario Odontológico"
  },
  {
    id: 5,
    descripcion:"Gasto Odontológico"
  },
  {
    id: 6,
    descripcion:"Gasto Bioquímico"
  },
  {
    id: 7,
    descripcion:"Gasto Radiológico"
  },
  {
    id: 8,
    descripcion:"Sanatorio Pensión"
  },
  {
    id: 9,
    descripcion:"Honorario Bioquímico"
  },
  {
    id: 10,
    descripcion:"Gasto Odontológico Prot."
  },
  {
    id: 11,
    descripcion:"NBU"
  },
  {
    id: 12,
    descripcion:"Gasto TAC"
  },
  {
    id: 13,
    descripcion:"Gasto Ecográfico"
  },
]

//CATEGORIAS EFECRTOR
export const CATEGORIAS_EFECTOR = {
  GASTO_ASISTENCIAL: 3,
  PRESTADOR: 18,
  HONORARIOS_MCP: 62
}

// MESA DE ENTRADA
export const MENU_MESA_ENTRADA = {
  DESELECCIONAR: 0,
  RECEPCION_COMPROBANTES: 1,
  GESTION_COMPROBANTES_PRESTADORES: 2,
  GESTION_COMPROBANTES_DOCUMENTO: 3,
};

export const MESA_ENTRADA_COMPROBANTES_ESTADOS = {
  PENDIENTE_ENVIO: 1,
  PROFORMA: 2,
  ANULADA: 3,
  ENVIADA: 4,
  ARCHIVADA: 5
};

export const MESA_ENTRADA_OFERENTE = {
  PRESTADORES: 1,
  PROVEEDORES: 2
}

export const MESA_ENTRADA_OFERENTE_ARRAY = [
  {id: MESA_ENTRADA_OFERENTE.PRESTADORES, descripcion: 'Prestadores', value: false},
  {id: MESA_ENTRADA_OFERENTE.PROVEEDORES, descripcion: 'Proveedores', value: true},
]

export const ESTADOS_COMRPOBANTES = {
  PENDIENTE_ENVIO: 1,
  ANULADA: 2,
  ENVIADA: 3,
  RETORNADA: 8,
  PROFORMA_ENVIADA: 10,
  PROFORMA_PAGADA: 11,
  PROFORMA_IMPUTADA: 12,
  PROFORMA_ASIGNADA: 13,
  PROFORMA_PENDIENTE: 14,
  ARCHIVADA: 15
}

export const MESA_ENTRADA_GESTION_BUTTONS = {
  ENVIAR: 0,
  ARCHIVAR: 1
}

export const CONDICION_IVA = {
  RESPONSABLE_INSCRIPTO: 1,
  MONOTRIBUTO: 2,
  EXENTO: 3,
  NO_RESPONSABLE: 4,
  MONOTRIBUTISTA_SOCIAL: 5,
};

export const CONDICION_IVA_ARRAY = [
  {id: CONDICION_IVA.RESPONSABLE_INSCRIPTO, descripcion: 'Responsable Inscripto'},
  {id: CONDICION_IVA.MONOTRIBUTO, descripcion: 'Monotributo'},
  {id: CONDICION_IVA.EXENTO, descripcion: 'Exento'},
  {id: CONDICION_IVA.NO_RESPONSABLE, descripcion: 'No Responsable'},
  {id: CONDICION_IVA.MONOTRIBUTISTA_SOCIAL, descripcion: 'Monotributista Social'},
];


export const PROVINCIAS = {
  CABA: 24
};

export const MOTIVO_BAJA_AFI = {
  FIN_DE_CONTRATO: 41,
  TRABAJADOR_TEMPORADA_RESERVA_PUESTO: 49
};

export const MENU_TIPO_EXPEDIENTE = {
  DESELECCIONAR: 0,
  PRESTADOR: 1,
  DOCUMENTO: 2,
};

export const MENU_TIPO_EXPEDIENTE_ARRAY = [
  {id: MENU_TIPO_EXPEDIENTE.PRESTADOR, descripcion: 'Comprobante Contratos'},
  {id: MENU_TIPO_EXPEDIENTE.DOCUMENTO, descripcion: 'Comprobante Documento'},
];

export const DATOS_COMPROBANTE = {
  TIPO_COMPROBANTE: 1,
  TIPO_FACTURA: 2,
  PROCEDENCIA: 3,
};

export const DESTINOS_COMPROBANTE ={
  LIQUIDACIONES: 1,
  LEGALES: 2,
  TESORERIA: 3,
  RRHH: 4,
  COMPRAS: 5,
  SECRETARIA_OSPEDYC: 6,
  SECRETARIA_ADMINISTRATIVA: 7,
  AFILIACIONES: 8,
  REINTEGRO_SUR: 9,
  TESORERIA_INTEGRACION: 10,
  AUDITORIA_MEDICA: 11,
  MESA_ENTRADA: 12,
};

export const TRAMITE_COMPROBANTE_DOCUMENTO = {
  CARTA_DOCUMENTO: 1,
  CARTA_DOCUMENTO_HOSPITALES: 2,
  CEDULA_NOTIFICACION: 3,
  DEFENSORIA_PUEBLO: 4,
  DEFENSA_CONSUMIDOR: 5,
  NOTA: 7,
  NOTA_SSS: 8,
  OFICIO_JUDICIAL: 9,
  TELEGRAMA: 11,
  DOCUMENTACION_AFILIACIONES: 22,
  DOCUMENTACION_COMPRAS: 23,
  DOCUMENTACION_TESORERIA: 24,
  DOCUMENTACION_SECRETARIA: 25,
  DOCUMENTACION_SUR: 26,
  DOCUMENTACION_RRHH: 27,
  EMBARGO: 29,
  REINTEGRO: 30,
}

export const TRAMITE_COMPROBANTE_DOCUMENTO_ARRAY = [
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.CARTA_DOCUMENTO, descripcion: 'Carta documento'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.CARTA_DOCUMENTO_HOSPITALES, descripcion: 'Carta documento Hospitales'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.CEDULA_NOTIFICACION, descripcion: 'Cédula de notificación'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.DEFENSORIA_PUEBLO, descripcion: 'Defensoría del pueblo'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.DEFENSA_CONSUMIDOR, descripcion: 'Defensa del consumidor'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.NOTA, descripcion: 'Nota'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.NOTA_SSS, descripcion: 'Nota SSS'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.OFICIO_JUDICIAL, descripcion: 'Oficio judicial'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.TELEGRAMA, descripcion: 'Telegrama'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.DOCUMENTACION_AFILIACIONES, descripcion: 'Documentación Afiliaciones'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.DOCUMENTACION_COMPRAS, descripcion: 'Documentación Compras'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.DOCUMENTACION_TESORERIA, descripcion: 'Documentación Tesoreria'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.DOCUMENTACION_SECRETARIA, descripcion: 'Documentación Secretaria'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.DOCUMENTACION_SUR, descripcion: 'Documentación SUR'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.DOCUMENTACION_RRHH, descripcion: 'Documentación RRHH'},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.EMBARGO, descripcion: "Embargo"},
  {id: TRAMITE_COMPROBANTE_DOCUMENTO.REINTEGRO, descripcion: "Reintegro"},
]

export const TRAMITE_COMPROBANTE_FACTURACION_PRESTADORES = {
  DIRECTORES_MEDICOS: 12,
  PRESTADORES: 13,
  PRESTADORES_HOSPITALES_PUBLICOS: 16,
  INTEGRACION: 28,
}

export const TRAMITE_COMPROBANTE_FACTURACION_PRESTADORES_ARRAY = [
  {id: TRAMITE_COMPROBANTE_FACTURACION_PRESTADORES.DIRECTORES_MEDICOS, descripcion: 'Facturación Directores Médicos'},
  {id: TRAMITE_COMPROBANTE_FACTURACION_PRESTADORES.PRESTADORES, descripcion: 'Facturación Prestadores'},
  {id: TRAMITE_COMPROBANTE_FACTURACION_PRESTADORES.PRESTADORES_HOSPITALES_PUBLICOS, descripcion: 'Facturación Prestadores Hospitales  Públicos'},
  {id: TRAMITE_COMPROBANTE_FACTURACION_PRESTADORES.INTEGRACION, descripcion: 'Facturacion prestadores de integracion'}
]

export const TRAMITE_COMPROBANTE_FACTURACION_PROVEEDORES = {
  PROVEEDORES: 14,
  COMPRAS_INSUMOS_MEDICOS: 15,
  SERVICIOS_COMPRAS: 17,
  SERVICIOS_SISTEMAS: 18,
  SERVICIOS_TESORERIA: 19,
  RECIBO: 20,
}

export const TRAMITE_COMPROBANTE_FACTURACION_PROVEEDORES_ARRAY = [
  {id: TRAMITE_COMPROBANTE_FACTURACION_PROVEEDORES.PROVEEDORES, descripcion: 'Facturación Proveedores'},
  {id: TRAMITE_COMPROBANTE_FACTURACION_PROVEEDORES.COMPRAS_INSUMOS_MEDICOS, descripcion: 'Facturación Compras-Insumos Médicos'},
  {id: TRAMITE_COMPROBANTE_FACTURACION_PROVEEDORES.SERVICIOS_COMPRAS, descripcion: 'Facturación de Servicios Compras'},
  {id: TRAMITE_COMPROBANTE_FACTURACION_PROVEEDORES.SERVICIOS_SISTEMAS, descripcion: 'Facturación de servicios Sistemas'},
  {id: TRAMITE_COMPROBANTE_FACTURACION_PROVEEDORES.SERVICIOS_TESORERIA, descripcion: 'Facturación de servicios Tesorería'},
  {id: TRAMITE_COMPROBANTE_FACTURACION_PROVEEDORES.RECIBO, descripcion: 'Recibo'},
]

export const LETRA_TIPO_FACTURA = {
  B: 2,
  C: 3,
}

export const STEPPER_EXPEDIENTE_FORM = {
  TRAMITE_COMPROBANTE: 0,
  DATOS_COMPROBANTE: 1,
  DOCUMENTACION: 2,
  IMPRESION: 3,
};

export const STEPPER_EXPEDIENTE_CONTABLES_FORM = {
  TRAMITE_COMPROBANTE: 0,
  DATOS_COMPROBANTE: 1,
  ASIENTOS_CONTABLES: 2,
  DOCUMENTACION: 3,
  IMPRESION: 4,
};

export const STEPPER_EXPEDIENTE_PROFORMA_FORM = {
  TRAMITE_COMPROBANTE: 0,
  PROFORMAS_PENDEINTES: 1,
  DATOS_COMPROBANTE: 2,
  DOCUMENTACION: 3,
  IMPRESION: 4,
};

export const STEPPER_EXPEDIENTE_CONTABLES_PROFORMA_FORM = {
  TRAMITE_COMPROBANTE: 0,
  PROFORMAS_PENDEINTES: 1,
  DATOS_COMPROBANTE: 2,
  ASIENTOS_CONTABLES: 3,
  DOCUMENTACION: 4,
  IMPRESION: 5,
};

export const TIPO_DOCUMENTACION_COMPROBANTE = {
  PRESTADORES_PROVEEDORES: 68,
  DOCUMENTO: 69,
};

export const MODULOS_APLICACION = {
  MESA_ENTRADA: 3
};

export const MENU_INFORMACION_EXPEDIENTES = {
  DATOS_TRAMITE: 0,
  DATOS_COMPROBANTE_PRESTADORES: 1,
  DATOS_COMPROBANTE_DOCUMENTO: 2,
  DATOS_CARGA: 3,
  DOCUMENTACION: 4,
  DATOS_PRESTADOR_PROVEEDOR: 5
};

export const ESTADO_MEDICACION_310 = {
  VIGENTES: 1,
  NO_VIGENTES: 2,
  TODOS: 3
};


export const TIPO_EMPADRONAMIENTO = {
  CELIAQUIA: 1,
  DIABETES: 2,
  DISCAPACIDAD: 3,
  HIPERTENSION: 4,
  HIV: 5,
  LECHES_MATERNIZADAS: 6,
  MEDICACION_ALTO_COSTO: 7,
  MEDICACION_CRONICA_100: 8,
  MEDICACION_CRONICA_70: 9,
  MEDICACION_CRONICA_40: 10,
  ONCOLOGIA: 11
};

export const STEPPER_EMPADRONAMIENTO = {
  BUSCAR_TITULAR: 0,
  DATOS_TITULAR: 1,
  DETALLE: 2,
  DOCUMENTACION: 3,
  MEDICAMENTOS: 4,
  CONFIRMACION: 5,
};

export const STEPPER_MEDICACION = {
  BUSCAR_TITULAR: 0,
  DATOS_TITULAR: 1,
  DETALLE: 2,
  MEDICAMENTOS: 3,
  CONFIRMACION: 4,
};

export const EMPADRONAMIENTO_SOLICITUDES_ESTADOS = {
  EN_CARGA: 1,
  PENDIENTE_REVISION: 2,
  PENDIENTE_AUTORIZACION: 3,
  ACTIVA: 4,
  RECHAZADA: 5,
  INACTIVA: 6
};

export const EMPADRONAMIENTO_MEDICACION_ESTADOS = {
  EN_CARGA: 1,
  PENDIENTE_REVISION: 2,
  PENDIENTE_AUTORIZACION: 3,
  AUTORIZADA: 4,
  RECHAZADA: 5
};

export const STEPPER_RECETAS = {
  BUSCAR_TITULAR: 0,
  DATOS_TITULAR: 1,
  DETALLE_RECETA: 2,
  MEDICAMENTOS: 3,
  CONFIRMACION: 4,
};

export const TIPOS_RECETAS = {
  SIMPLE: 1,
  DUPLICADA: 2
};

export const RECETAS_ESTADOS = {
  EN_CARGA: 1,
  FINALIZADA: 2
};

export const RECETAS_MENU_GESTION = {
  AFILIADO: 0,
  ADMINISTRAR: 1,
  INFORMACION: 2,
  PRACTICAS: 3,
  NOTAS: 4,
  OBSERVACIONES: 5,
};

export const EMPADRONAMIENTO_MENU_GESTION = {
  AFILIADO: 0,
  ADMINISTRAR: 1,
  INFORMACION: 2,
  DOCUMENTACION: 3
};

export const MENU_EMPADRONAMIENTO = {
  INGRESO_SOLICITUD: 1,
  GESTION_BANDEJA: 2,
  CONSULTA_EMPADRONAMIENTOS: 3
};

export const MENU_RECETAS = {
  INGRESO_RECETA: 1,
  GESTION_HISTORIAL: 2
};

export const ROLES = {
  RECETAS_DIGITALES: 50,
  TOTEM: 56,
};

  
export const ESTADOS_COTIZACIONES = {
  PENDIENTE_COTIZACION : 5, //corresponde al id de estado de autorizacion solicitudes
  COTIZACIONES_SOLICITADAS : 2,
  PENDIENTE_ACEPTACION : 3,
  COTIZACIONES_ACEPTADAS : 4
};

export const ESTADOS_AUDITORIAFACTURACION_COMPRAS = {
  COMPROBANTE: 1, 
  PENDIENTE_ENVIO: 2,
  PENDIENTE_PAGO:3,
  RECHAZADAS : 4
}
export const PROCEDENCIA = {
  CORREO: 1,
  MANO: 2,
  OTRAS_AREAS: 3,
  MAIL: 4,
  ALBERTI: 5,
  MEXICO: 6,
}


export const MODULO_APLICACION = {
  AFILIACIONES: 1,
  CONTRATACIONES: 2,
  MESA_ENTRADA: 3
}

export const TIPO_COMPROBANTE_DOCUMENTO = {
  DOCUMENTACION: 1,
  EMBARGO: 2,
}

export const COMPROBANTE_EMBARGO_ARRAY = [
  {descripcion: "Documentación", value: TIPO_COMPROBANTE_DOCUMENTO.DOCUMENTACION},
  {descripcion: "Embargo", value: TIPO_COMPROBANTE_DOCUMENTO.EMBARGO}
]

export const AREAS_FISICAS = {
  LIQUIDACIONES: 1,
  LEGALES: 2,
  TESORERIA: 3,
  RRHH: 4,
  COMPRAS: 5,
  SECRETARIA_OSPEDYC: 6,
  SECRETARIA_ADMINISTRATIVA: 7,
  AFILIACIONES: 8,
  REINTEGRO_SUR: 9,
  TESORERIA_INTEGRACION: 10,
  AUDITORIA_MEDICA: 11,
  MESA_ENTRADA: 12,
};

export const SUB_AREAS_FISICAS = {
  ALBERTI: 1,
  MATHEU: 2,
};

export const HISTORIAL_COTIZACIONES ={
  COTIZACIONES: 1,
  MATERIALES: 2
}